[package]
name = "velocache"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
clap = { version = "4.0", features = ["derive"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.13"
lru = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-util = { version = "0.7", features = ["codec"] }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
anyhow = "1.0"
futures-util = "0.3"
md5 = "0.7"
bincode = "1.3"
atty = "0.2"