[proxy]
port = 3128
bind_address = "0.0.0.0" # "127.0.0.1" yerine "0.0.0.0" yazın
user_agent = "VeloCache/1.0"

[cache]
# Bellekte tutulacak maksimum öğe sayısı
memory_items = 1000
# Cache'lenen dosyaların diske yazılacağı klasör. Boş bırakırsanız disk cache devre dışı kalır.
disk_path = "./.cache"
# Cache'lenen bir öğenin maksimum TTL süresi (saniye cinsinden)
ttl_seconds = 86400 # 24 saat

[management]
port = 8080
bind_address = "127.0.0.1" # Yönetim paneli güvenlik için localhost'ta kalabilir

[log]
level = "info" # debug, info, warn, error