[proxy]
port = 3128
bind_address = "0.0.0.0"
user_agent = "VeloCache/1.0"

[cache]
memory_items = 1000
disk_path = "./.cache"
ttl_seconds = 86400 # 24 saat

[management]
port = 8080
bind_address = "127.0.0.1"

[log]
level = "info" # debug, info, warn, error

[certs]
path = "./certs" # Sertifika dosyalarının saklanacağı dizin